<a href="https://colab.research.google.com/github/Toulouse08/IS-170-Machine-Learning/blob/Naive-Bayes/Lab8_Naive_bayes_Talib_Fuentes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Mohammed Talib & Edwin Fuentes -- Lab8 - Naive-Bayes

Resources used.

https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset

#Naive-Bayes with wine Data

In [ ]:
from sklearn import datasets
import pandas as pd

#load dataset
wine=datasets.load_wine()

In [ ]:
df=pd.read_csv("wine.csv")
df.head()

,Wine_type,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [ ]:
df.columns= ['class', 'alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline',]
df.head()

,class,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [ ]:
x_data = df[['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']]
y_data = df['class']

In [ ]:
# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.3) # 70% training and 30% test

In [ ]:
#This is model generation

#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
model = GaussianNB()

#Train the model using the training sets
model.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = model.predict(X_test)

#This is to evaluate the model
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9629629629629629

#Naive-Bayes with Brain stroke Data

In [ ]:
df1=pd.read_csv("strokedata.csv")
df1.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [ ]:
df1.tail()

,gender,age,hypertension,heart_disease,ever_married,avg_glucose_level,bmi,smoking_status,stroke
5105,Female,80.0,1,0,Yes,83.75,NaN,never smoked,0
5106,Female,81.0,0,0,Yes,125.20,40.0,never smoked,0
5107,Female,35.0,0,0,Yes,82.99,30.6,never smoked,0
5108,Male,51.0,0,0,Yes,166.29,25.6,formerly smoked,0
5109,Female,44.0,0,0,Yes,85.28,26.2,Unknown,0

In [ ]:
df1.columns

Index(['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='object')

In [ ]:
df1=df1[['gender','age','hypertension','heart_disease','ever_married','avg_glucose_level','bmi','smoking_status','stroke']]

In [ ]:
df1.columns

Index(['gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'avg_glucose_level', 'bmi', 'smoking_status', 'stroke'],
      dtype='object')

In [ ]:
df1.head()

,gender,age,hypertension,heart_disease,ever_married,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67.0,0,1,Yes,228.69,36.6,formerly smoked,1
1,Female,61.0,0,0,Yes,202.21,NaN,never smoked,1
2,Male,80.0,0,1,Yes,105.92,32.5,never smoked,1
3,Female,49.0,0,0,Yes,171.23,34.4,smokes,1
4,Female,79.0,1,0,Yes,174.12,24.0,never smoked,1

In [ ]:
#In order to process we must turn those categorical values into numberic values
#Import LabelEncoder
from sklearn import preprocessing

#creating labelEncoder
le = preprocessing.LabelEncoder()

#Using .fit_transform function to fit label
#encoder and return encoded label
gender_label=le.fit_transform(df1['gender'])

#printing gender_label
gender_label

array([1, 0, 1, ..., 0, 1, 0])

In [ ]:


#Using .fit_transform function to fit label
#encoder and return encoded label
married_label=le.fit_transform(df1['ever_married'])

#printing gender_label
married_label

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:


#Using .fit_transform function to fit label
#encoder and return encoded label
smoking_label=le.fit_transform(df1['smoking_status'])

#printing gender_label
smoking_label

array([1, 2, 2, ..., 2, 1, 0])

In [ ]:

age_label=df1['age']


age_label

0       67.0
1       61.0
2       80.0
3       49.0
4       79.0
        ...
5105    80.0
5106    81.0
5107    35.0
5108    51.0
5109    44.0
Name: age, Length: 5110, dtype: float64

In [ ]:
hypertension_label=df1['hypertension']


hypertension_label

0       0
1       0
2       0
3       0
4       1
       ..
5105    1
5106    0
5107    0
5108    0
5109    0
Name: hypertension, Length: 5110, dtype: int64

In [ ]:
heart_label=df1['heart_disease']


heart_label

0       1
1       0
2       1
3       0
4       0
       ..
5105    0
5106    0
5107    0
5108    0
5109    0
Name: heart_disease, Length: 5110, dtype: int64

In [ ]:
glucose_label=df1['avg_glucose_level']


glucose_label

0       228.69
1       202.21
2       105.92
3       171.23
4       174.12
         ...
5105     83.75
5106    125.20
5107     82.99
5108    166.29
5109     85.28
Name: avg_glucose_level, Length: 5110, dtype: float64

In [ ]:
bmi_label=df1['bmi']


bmi_label

0       36.6
1        NaN
2       32.5
3       34.4
4       24.0
        ...
5105     NaN
5106    40.0
5107    30.6
5108    25.6
5109    26.2
Name: bmi, Length: 5110, dtype: float64

In [ ]:
stroke_target=df1['stroke']


stroke_target

0       1
1       1
2       1
3       1
4       1
       ..
5105    0
5106    0
5107    0
5108    0
5109    0
Name: stroke, Length: 5110, dtype: int64

In [ ]:
df1.head()

,gender,age,hypertension,heart_disease,ever_married,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67.0,0,1,Yes,228.69,36.6,formerly smoked,1
1,Female,61.0,0,0,Yes,202.21,NaN,never smoked,1
2,Male,80.0,0,1,Yes,105.92,32.5,never smoked,1
3,Female,49.0,0,0,Yes,171.23,34.4,smokes,1
4,Female,79.0,1,0,Yes,174.12,24.0,never smoked,1

In [ ]:
#we'll use zip method in this function called merge to combine the two labels: weather and temp
def merge (list1, list2, list3, list4, list5, list6, list7, list8):
  merged_list=tuple(zip(list1, list2, list3, list4, list5, list6, list7, list8))
  return merged_list

features=merge(smoking_label, married_label, age_label, gender_label, hypertension_label, heart_label, glucose_label, bmi_label)
features

((1, 1, 67.0, 1, 0, 1, 228.69, 36.6),
 (2, 1, 61.0, 0, 0, 0, 202.21, nan),
 (2, 1, 80.0, 1, 0, 1, 105.92, 32.5),
 (3, 1, 49.0, 0, 0, 0, 171.23, 34.4),
 (2, 1, 79.0, 0, 1, 0, 174.12, 24.0),
 (1, 1, 81.0, 1, 0, 0, 186.21, 29.0),
 (2, 1, 74.0, 1, 1, 1, 70.09, 27.4),
 (2, 0, 69.0, 0, 0, 0, 94.39, 22.8),
 (0, 1, 59.0, 0, 0, 0, 76.15, nan),
 (0, 1, 78.0, 0, 0, 0, 58.57, 24.2),
 (2, 1, 81.0, 0, 1, 0, 80.43, 29.7),
 (3, 1, 61.0, 0, 0, 1, 120.46, 36.8),
 (3, 1, 54.0, 0, 0, 0, 104.51, 27.3),
 (0, 1, 78.0, 1, 0, 1, 219.84, nan),
 (2, 1, 79.0, 0, 0, 1, 214.09, 28.2),
 (2, 1, 50.0, 0, 1, 0, 167.41, 30.9),
 (3, 1, 64.0, 1, 0, 1, 191.61, 37.5),
 (3, 1, 75.0, 1, 1, 0, 221.29, 25.8),
 (2, 0, 60.0, 0, 0, 0, 89.22, 37.8),
 (0, 0, 57.0, 1, 0, 1, 217.08, nan),
 (3, 1, 71.0, 0, 0, 0, 193.94, 22.4),
 (2, 1, 52.0, 0, 1, 0, 233.29, 48.9),
 (2, 1, 79.0, 0, 0, 0, 228.7, 26.6),
 (0, 1, 82.0, 1, 0, 1, 208.3, 32.5),
 (1, 1, 71.0, 1, 0, 0, 102.87, 27.2),
 (2, 1, 80.0, 1, 0, 0, 104.12, 23.5),
 (1, 1, 65.0, 0, 0, 0, 100.98, 28.2),
 (0, 1, 58.0, 1, 0, 0, 189.84, nan),
 (3, 1, 69.0, 1, 0, 1, 195.23, 28.3),
 (1, 1, 59.0, 1, 0, 0, 211.78, nan),
 (3, 1, 57.0, 1, 1, 0, 212.08, 44.2),
 (0, 1, 42.0, 1, 0, 0, 83.41, 25.4),
 (2, 1, 82.0, 0, 1, 0, 196.92, 22.2),
 (1, 1, 80.0, 1, 0, 1, 252.72, 30.5),
 (2, 0, 48.0, 1, 0, 0, 84.2, 29.7),
 (1, 0, 82.0, 0, 1, 1, 84.03, 26.5),
 (1, 1, 74.0, 1, 0, 0, 219.72, 33.7),
 (1, 1, 72.0, 0, 1, 0, 74.63, 23.1),
 (0, 0, 58.0, 1, 0, 0, 92.62, 32.0),
 (2, 1, 49.0, 0, 0, 0, 60.91, 29.9),
 (1, 1, 78.0, 1, 0, 0, 78.03, 23.9),
 (2, 1, 54.0, 1, 0, 0, 71.22, 28.5),
 (3, 1, 82.0, 1, 0, 1, 144.9, 26.4),
 (1, 1, 63.0, 0, 0, 0, 90.9, nan),
 (3, 1, 60.0, 1, 1, 0, 213.03, 20.2),
 (2, 1, 76.0, 1, 1, 0, 243.58, 33.6),
 (0, 0, 75.0, 0, 0, 1, 109.78, nan),
 (1, 1, 58.0, 0, 0, 0, 107.26, 38.6),
 (2, 1, 81.0, 1, 0, 0, 99.33, 33.7),
 (3, 1, 39.0, 0, 1, 0, 58.09, 39.2),
 (0, 0, 76.0, 0, 0, 0, 89.96, nan),
 (1, 1, 78.0, 1, 1, 0, 75.32, nan),
 (2, 1, 79.0, 0, 0, 1, 127.29, 27.7),
 (2, 1, 77.0, 0, 1, 0, 124.13, 31.4),
 (2, 1, 63.0, 0, 0, 0, 197.54, nan),
 (1, 1, 63.0, 1, 0, 1, 196.71, 36.5),
 (2, 1, 82.0, 0, 0, 0, 59.32, 33.2),
 (1, 1, 78.0, 1, 0, 0, 237.75, nan),
 (2, 1, 73.0, 1, 1, 0, 194.99, 32.8),
 (2, 1, 54.0, 0, 1, 0, 180.93, 27.7),
 (1, 1, 56.0, 0, 0, 0, 185.17, 40.4),
 (2, 1, 80.0, 0, 1, 0, 74.9, 22.2),
 (3, 1, 67.0, 0, 1, 0, 61.94, 25.3),
 (1, 1, 45.0, 0, 0, 0, 93.72, 30.2),
 (0, 1, 75.0, 1, 0, 0, 104.72, nan),
 (2, 0, 78.0, 1, 1, 0, 113.01, 24.0),
 (2, 1, 70.0, 0, 0, 0, 221.58, 47.5),
 (0, 1, 76.0, 1, 0, 0, 104.47, 20.3),
 (1, 1, 59.0, 1, 0, 0, 86.23, 30.0),
 (2, 1, 80.0, 0, 1, 0, 72.67, 28.9),
 (1, 1, 76.0, 0, 0, 0, 62.57, nan),
 (1, 1, 67.0, 0, 1, 0, 179.12, 28.1),
 (1, 1, 66.0, 0, 1, 0, 116.55, 31.1),
 (2, 1, 63.0, 1, 0, 0, 228.56, 27.4),
 (2, 1, 52.0, 0, 0, 0, 96.59, 26.4),
 (1, 1, 80.0, 0, 0, 1, 66.72, 21.7),
 (2, 1, 80.0, 1, 1, 0, 240.09, 27.0),
 (1, 1, 79.0, 0, 0, 0, 110.85, 24.1),
 (2, 1, 51.0, 0, 0, 0, 165.31, nan),
 (0, 1, 43.0, 1, 0, 0, 143.43, 45.9),
 (0, 1, 59.0, 1, 0, 0, 96.16, 44.1),
 (0, 1, 66.0, 0, 0, 0, 101.45, nan),
 (2, 0, 79.0, 0, 0, 0, 88.92, 22.9),
 (2, 0, 68.0, 0, 1, 0, 79.79, 29.7),
 (0, 1, 58.0, 1, 0, 0, 71.2, nan),
 (3, 1, 54.0, 1, 0, 0, 96.97, 29.1),
 (3, 1, 61.0, 1, 0, 1, 111.81, 27.3),
 (1, 1, 70.0, 0, 0, 1, 59.35, 32.3),
 (1, 1, 47.0, 1, 0, 0, 86.94, 41.1),
 (0, 1, 74.0, 1, 0, 0, 98.55, 25.6),
 (2, 1, 79.0, 0, 0, 1, 226.98, 29.8),
 (2, 1, 81.0, 1, 0, 0, 72.81, 26.3),
 (2, 0, 57.0, 0, 0, 0, 68.02, 37.5),
 (0, 1, 80.0, 0, 1, 0, 68.56, 26.2),
 (2, 1, 45.0, 1, 0, 0, 64.14, 29.4),
 (2, 1, 78.0, 0, 0, 0, 235.63, 32.3),
 (1, 1, 70.0, 0, 0, 0, 76.34, 24.4),
 (3, 1, 58.0, 1, 0, 1, 240.59, 31.4),
 (1, 1, 57.0, 1, 1, 0, 78.92, 27.7),
 (2, 1, 69.0, 0, 0, 0, 82.81, 28.0),
 (0, 1, 64.0, 1, 0, 1, 74.1, 28.8),
 (2, 1, 77.0, 0, 0, 0, 190.32, 31.4),
 (1, 1, 74.0, 0, 0, 0, 231.61, 34.6),
 (0, 1, 81.0, 0, 0, 1, 78.7, 19.4),
 (0, 1, 57.0, 0, 0, 0, 110.52, 28.5),
 (3, 1, 58.0, 1, 0, 0, 82.3, nan),
 (1, 1, 50.0, 0, 1, 0, 73.18, 30.3),
 (3, 1, 54.0, 0, 0, 0, 191.82, 40.4),
 (2, 1, 79.0, 0, 0, 0, 93.05, 24.2),
 (2, 1, 53.0, 0, 0, 0, 64.17, 41.5),
 (1, 1, 79.0, 1, 0, 1, 129.98, 22.6),
 (3, 1, 80.0, 1, 0, 1, 68.53, 24.2),
 (1, 1, 76.0, 0, 0, 0, 106.41, nan),
 (2, 1, 45.0, 0, 0, 0, 224.1, 56.6),
 (0, 0, 68.0, 0, 0, 0, 82.1, 27.1),
 (2, 0, 71.0, 1, 1, 1, 216.94, 30.9),
 (3, 1, 61.0, 1, 1, 0, 76.11, 27.3),
 (3, 1, 74.0, 1, 0, 0, 72.96, 31.3),
 (1, 0, 38.0, 0, 0, 0, 82.28, 24.0),
 (2, 1, 77.0, 0, 0, 0, 105.22, 31.0),
 (1, 1, 58.0, 0, 0, 0, 59.86, 28.0),
 (0, 1, 53.0, 0, 1, 0, 62.55, 30.3),
 (3, 1, 80.0, 1, 0, 0, 259.63, 31.7),
 (2, 1, 56.0, 1, 1, 0, 249.31, 35.8),
 (0, 1, 72.0, 0, 0, 0, 219.91, nan),
 (2, 1, 72.0, 0, 0, 0, 131.41, 28.4),
 (1, 1, 78.0, 1, 1, 0, 93.13, nan),
 (0, 1, 80.0, 0, 0, 0, 73.54, 24.0),
 (1, 1, 82.0, 1, 0, 0, 200.59, 29.0),
 (0, 1, 75.0, 0, 0, 0, 62.48, nan),
 (2, 1, 73.0, 0, 1, 0, 190.14, 36.5),
 (2, 0, 78.0, 0, 1, 0, 130.54, 20.1),
 (2, 0, 69.0, 1, 1, 0, 182.99, 36.5),
 (1, 1, 38.0, 0, 0, 0, 101.45, nan),
 (2, 1, 68.0, 0, 1, 0, 206.09, 26.7),
 (2, 1, 71.0, 0, 0, 0, 263.32, 38.7),
 (1, 1, 76.0, 1, 0, 0, 140.1, 29.9),
 (0, 1, 76.0, 0, 0, 0, 207.28, 34.9),
 (1, 1, 76.0, 1, 1, 0, 194.37, 27.0),
 (0, 1, 75.0, 0, 0, 0, 199.2, 26.6),
 (2, 1, 82.0, 1, 0, 1, 103.68, 25.0),
 (3, 1, 59.0, 0, 0, 0, 116.44, 23.8),
 (2, 1, 74.0, 0, 1, 0, 70.28, 21.8),
 (2, 0, 69.0, 0, 1, 1, 72.17, 36.8),
 (2, 1, 72.0, 0, 1, 0, 221.79, 30.0),
 (1, 1, 66.0, 1, 0, 0, 151.16, 27.5),
 (1, 1, 65.0, 1, 0, 0, 68.43, nan),
 (2, 1, 78.0, 0, 0, 0, 67.29, 24.6),
 (2, 1, 57.0, 0, 1, 0, 67.41, 32.9),
 (2, 1, 70.0, 0, 0, 1, 239.07, 26.1),
 (0, 1, 79.0, 0, 0, 0, 169.67, nan),
 (1, 1, 68.0, 1, 0, 1, 223.83, 31.9),
 (2, 1, 80.0, 0, 0, 0, 76.57, 34.1),
 (3, 1, 68.0, 1, 0, 0, 77.82, 27.5),
 (2, 1, 55.0, 0, 0, 0, 92.98, 25.6),
 (2, 1, 77.0, 0, 0, 1, 231.56, 36.9),
 (3, 1, 50.0, 0, 0, 0, 102.16, 31.4),
 (3, 1, 57.0, 0, 0, 0, 221.89, 37.3),
 (1, 1, 71.0, 0, 0, 0, 195.71, 34.1),
 (2, 1, 81.0, 0, 1, 0, 74.02, 25.0),
 (1, 1, 76.0, 0, 0, 0, 57.92, nan),
 (3, 1, 71.0, 1, 0, 1, 81.76, nan),
 (0, 0, 1.32, 0, 0, 0, 70.37, nan),
 (2, 0, 78.0, 0, 1, 0, 203.87, 45.7),
 (1, 1, 70.0, 0, 1, 0, 89.13, 34.2),
 (1, 1, 78.0, 1, 0, 0, 133.19, 23.6),
 (0, 1, 56.0, 0, 0, 0, 162.23, 27.3),
 (2, 1, 79.0, 1, 1, 0, 75.02, nan),
 (1, 0, 79.0, 0, 1, 0, 98.02, 22.3),
 (2, 1, 81.0, 1, 0, 0, 91.54, 31.4),
 (1, 1, 64.0, 1, 0, 0, 111.98, nan),
 (2, 0, 79.0, 0, 1, 1, 60.94, nan),
 (3, 1, 60.0, 0, 0, 0, 97.43, 26.4),
 (1, 1, 80.0, 0, 1, 0, 91.02, 32.9),
 (1, 1, 78.0, 0, 0, 0, 60.67, nan),
 (2, 1, 72.0, 1, 1, 0, 185.49, 37.1),
 (2, 1, 80.0, 0, 0, 0, 64.44, 45.0),
 (1, 1, 78.0, 1, 1, 0, 56.11, 25.5),
 (0, 1, 80.0, 0, 0, 0, 110.66, nan),
 (0, 1, 81.0, 1, 0, 0, 213.22, 26.1),
 (2, 1, 46.0, 0, 0, 0, 78.18, 30.8),
 (1, 1, 59.0, 1, 0, 0, 111.04, 32.0),
 (3, 1, 32.0, 0, 0, 0, 76.13, 29.9),
 (0, 0, 77.0, 0, 0, 0, 81.32, nan),
 (3, 1, 61.0, 1, 1, 1, 112.24, 37.4),
 (1, 1, 63.0, 1, 0, 0, 137.3, 31.7),
 (1, 1, 63.0, 1, 0, 1, 116.69, 34.5),
 (1, 1, 82.0, 0, 1, 1, 215.94, 27.9),
 (1, 1, 82.0, 1, 0, 0, 86.62, 29.5),
 (0, 1, 61.0, 1, 0, 1, 209.86, nan),
 (1, 1, 65.0, 0, 0, 0, 205.77, 46.0),
 (1, 1, 51.0, 1, 1, 0, 112.16, 42.5),
 (3, 1, 59.0, 1, 0, 0, 118.03, 35.5),
 (3, 1, 68.0, 1, 1, 1, 271.74, 31.1),
 (3, 1, 72.0, 0, 0, 0, 97.92, 26.9),
 (1, 1, 59.0, 1, 0, 0, 200.62, 35.8),
 (1, 1, 70.0, 1, 1, 0, 242.52, 45.5),
 (0, 1, 69.0, 1, 0, 0, 93.81, 28.5),
 (1, 1, 79.0, 1, 0, 0, 114.77, nan),
 (2, 1, 74.0, 0, 0, 0, 74.96, 26.6),
 (0, 1, 74.0, 1, 0, 0, 167.13, nan),
 (1, 1, 80.0, 1, 1, 1, 175.29, 31.5),
 (2, 1, 77.0, 0, 0, 0, 90.0, 32.0),
 (2, 1, 78.0, 0, 0, 0, 109.47, 30.8),
 (3, 1, 54.0, 1, 0, 0, 87.85, 31.1),
 (1, 1, 78.0, 0, 0, 0, 106.74, 33.0),
 (2, 1, 81.0, 0, 0, 0, 80.13, 23.4),
 (2, 0, 78.0, 1, 0, 0, 90.19, 26.9),
 (0, 1, 78.0, 1, 1, 0, 134.8, 33.6),
 (0, 1, 63.0, 0, 0, 0, 106.58, 23.9),
 (2, 1, 39.0, 0, 0, 0, 83.24, 26.3),
 (1, 1, 51.0, 0, 0, 0, 103.43, 27.3),
 (2, 1, 63.0, 1, 0, 0, 208.65, 30.7),
 (2, 1, 48.0, 0, 0, 0, 74.11, 20.5),
 (2, 1, 81.0, 0, 0, 0, 95.84, 21.5),
 (3, 0, 79.0, 0, 0, 1, 205.33, 31.0),
 (2, 1, 78.0, 1, 0, 0, 116.1, 27.1),
 (3, 1, 55.0, 0, 1, 1, 210.4, 40.0),
 (3, 1, 76.0, 0, 1, 1, 199.86, nan),
 (2, 1, 73.0, 1, 0, 1, 219.73, 28.6),
 (3, 1, 81.0, 1, 1, 1, 250.89, 28.1),
 (2, 1, 79.0, 1, 0, 0, 72.73, 28.4),
 (1, 1, 63.0, 0, 0, 0, 205.35, 42.2),
 (3, 0, 81.0, 0, 0, 0, 70.3, 25.8),
 (3, 0, 49.0, 1, 0, 0, 104.86, 31.9),
 (0, 1, 57.0, 0, 0, 1, 216.58, 31.0),
 (2, 1, 81.0, 0, 0, 0, 184.4, 27.5),
 (2, 1, 74.0, 1, 0, 0, 60.98, nan),
 (3, 1, 39.0, 0, 0, 0, 97.76, 29.6),
 (2, 0, 80.0, 0, 1, 0, 66.03, 35.4),
 (2, 1, 81.0, 0, 0, 0, 81.95, 16.9),
 (3, 1, 79.0, 0, 0, 0, 97.73, 21.5),
 (2, 1, 73.0, 0, 0, 0, 70.94, 34.4),
 (1, 1, 77.0, 0, 1, 0, 199.84, 28.0),
 (0, 1, 78.0, 1, 0, 0, 218.46, 26.8),
 (0, 1, 68.0, 0, 0, 0, 211.06, 39.3),
 (0, 1, 57.0, 1, 0, 0, 86.3, 31.7),
 (1, 1, 77.0, 1, 0, 0, 162.14, 32.6),
 (2, 1, 51.0, 0, 1, 0, 88.2, 28.4),
 (3, 1, 60.0, 1, 0, 1, 91.92, 35.9),
 (1, 1, 66.0, 1, 0, 0, 76.46, 21.2),
 (1, 1, 57.0, 1, 0, 0, 197.28, 34.5),
 (2, 1, 68.0, 1, 0, 0, 233.94, 42.4),
 (1, 1, 68.0, 0, 1, 1, 247.51, 40.5),
 (0, 1, 57.0, 1, 0, 0, 84.96, 36.7),
 (0, 0, 14.0, 0, 0, 0, 57.93, 30.9),
 (1, 1, 75.0, 0, 0, 0, 78.8, 29.3),
 (0, 1, 71.0, 1, 1, 0, 87.8, nan),
 (0, 1, 78.0, 0, 0, 0, 78.81, 19.6),
 (0, 0, 3.0, 1, 0, 0, 95.12, 18.0),
 (2, 1, 58.0, 1, 1, 0, 87.96, 39.2),
 (0, 0, 8.0, 0, 0, 0, 110.89, 17.6),
 (1, 1, 70.0, 0, 0, 0, 69.04, 35.9),
 (0, 0, 14.0, 1, 0, 0, 161.28, 19.1),
 (0, 1, 47.0, 0, 0, 0, 210.95, 50.1),
 (1, 1, 52.0, 0, 0, 0, 77.59, 17.7),
 (2, 1, 75.0, 0, 0, 1, 243.53, 27.0),
 (3, 1, 32.0, 0, 0, 0, 77.67, 32.3),
 (2, 1, 74.0, 0, 1, 0, 205.84, 54.6),
 (0, 1, 79.0, 0, 0, 0, 77.08, 35.0),
 (1, 1, 79.0, 1, 0, 1, 57.08, 22.0),
 (2, 1, 37.0, 0, 0, 0, 162.96, 39.4),
 (1, 1, 37.0, 0, 0, 0, 73.5, 26.1),
 (2, 1, 40.0, 0, 0, 0, 95.04, 42.4),
 (2, 0, 35.0, 1, 0, 0, 85.37, 33.0),
 (3, 0, 20.0, 0, 0, 0, 84.62, 19.7),
 (2, 1, 42.0, 0, 0, 0, 82.67, 22.5),
 (3, 1, 44.0, 0, 0, 0, 57.33, 24.6),
 (3, 1, 79.0, 0, 0, 1, 67.84, 25.2),
 (0, 1, 65.0, 0, 1, 0, 75.7, 41.8),
 (3, 1, 57.0, 0, 1, 0, 129.54, 60.9),
 (3, 1, 49.0, 0, 0, 0, 60.22, 31.5),
 (1, 1, 71.0, 1, 0, 0, 198.21, 27.3),
 (2, 1, 59.0, 0, 0, 0, 109.82, 23.7),
 (2, 1, 25.0, 0, 0, 0, 60.84, 24.5),
 (3, 1, 67.0, 0, 0, 0, 94.61, 28.4),
 (2, 0, 38.0, 0, 0, 0, 97.49, 26.9),
 (2, 1, 54.0, 0, 0, 0, 206.72, 26.7),
 (2, 1, 70.0, 0, 0, 0, 214.45, 31.2),
 (0, 1, 27.0, 1, 0, 0, 82.9, 25.0),
 (0, 1, 47.0, 0, 0, 0, 103.26, 25.4),
 (3, 0, 58.0, 1, 1, 0, 55.78, 27.5),
 (0, 0, 3.0, 0, 0, 0, 73.74, 16.0),
 (0, 1, 58.0, 0, 0, 0, 149.75, 27.0),
 (0, 0, 14.0, 1, 0, 0, 82.34, 31.6),
 (1, 1, 32.0, 0, 0, 0, 62.6, 25.1),
 (2, 0, 23.0, 0, 0, 0, 94.09, 30.9),
 (0, 1, 55.0, 0, 0, 0, 55.42, 24.8),
 (0, 0, 17.0, 0, 0, 0, 82.18, 23.4),
 (3, 1, 59.0, 1, 0, 0, 117.92, 29.4),
 (0, 0, 13.0, 1, 0, 0, 114.84, 18.3),
 (0, 0, 4.0, 1, 0, 0, 79.17, 20.0),
 (0, 0, 16.0, 0, 0, 0, 110.63, 19.5),
 (1, 1, 67.0, 1, 0, 0, 190.7, 36.0),
 (0, 0, 22.0, 0, 0, 0, 79.81, 27.7),
 (3, 1, 45.0, 0, 0, 0, 113.63, 27.5),
 (2, 1, 66.0, 0, 0, 0, 141.24, 28.5),
 (3, 1, 58.0, 1, 1, 0, 56.96, 26.8),
 (2, 1, 69.0, 1, 0, 0, 203.04, 33.6),
 (0, 1, 58.0, 0, 0, 0, 94.3, 29.1),
 (0, 1, 53.0, 0, 0, 0, 81.51, 28.5),
 (1, 0, 78.0, 0, 0, 0, 137.74, 34.9),
 (2, 1, 44.0, 1, 0, 0, 81.84, 25.1),
 (3, 1, 66.0, 1, 0, 0, 242.3, 35.3),
 (3, 1, 27.0, 1, 0, 0, 102.64, 26.4),
 (3, 1, 43.0, 1, 0, 0, 146.01, 31.5),
 (0, 0, 13.0, 0, 0, 0, 75.42, 40.1),
 (0, 1, 51.0, 1, 0, 0, 220.49, 43.1),
 (3, 1, 30.0, 0, 0, 0, 61.45, 36.7),
 (1, 1, 46.0, 1, 0, 0, 88.19, 29.3),
 (0, 1, 43.0, 0, 0, 0, 115.22, 21.2),
 (0, 1, 79.0, 0, 0, 0, 97.93, 31.2),
 (0, 1, 27.0, 0, 0, 0, 85.6, 21.4),
 (3, 1, 38.0, 0, 0, 0, 79.83, 27.9),
 (2, 1, 78.0, 0, 1, 0, 218.46, 34.3),
 (1, 1, 57.0, 1, 0, 1, 62.2, 31.0),
 (1, 1, 61.0, 1, 0, 0, 69.15, 27.7),
 (2, 1, 37.0, 0, 1, 0, 127.71, 36.0),
 (1, 1, 48.0, 0, 0, 0, 216.7, 38.7),
 (2, 0, 29.0, 0, 0, 0, 71.89, 27.6),
 (0, 0, 22.0, 1, 0, 0, 103.56, 25.1),
 (0, 0, 11.0, 1, 0, 0, 79.03, 16.5),
 (0, 0, 22.0, 0, 0, 0, 69.94, 22.8),
 (0, 1, 53.0, 1, 0, 0, 90.12, 35.4),
 (1, 0, 27.0, 1, 0, 0, 95.1, 24.3),
 (1, 1, 76.0, 1, 0, 0, 234.58, 34.3),
 (2, 1, 57.0, 0, 1, 0, 235.85, 40.1),
 (0, 0, 8.0, 1, 0, 0, 78.05, 25.7),
 (3, 0, 21.0, 0, 0, 0, 89.44, 21.9),
 (3, 0, 18.0, 0, 0, 0, 111.38, 38.4),
 (2, 1, 78.0, 0, 0, 0, 243.5, 26.1),
 (1, 1, 78.0, 0, 1, 0, 182.2, 30.5),
 (3, 1, 33.0, 1, 0, 0, 229.92, 25.9),
 (1, 1, 52.0, 0, 0, 0, 82.24, 54.7),
 (0, 1, 51.0, 0, 0, 0, 89.84, 29.9),
 (0, 0, 11.0, 1, 0, 0, 90.69, 18.6),
 (0, 1, 48.0, 0, 0, 0, 84.38, 27.1),
 (2, 0, 82.0, 0, 0, 1, 215.6, 24.9),
 (2, 1, 54.0, 0, 0, 0, 91.61, 25.2),
 (2, 1, 49.0, 0, 0, 0, 138.16, 19.4),
 (2, 1, 24.0, 0, 0, 0, 75.23, 29.0),
 (1, 1, 37.0, 0, 0, 0, 75.18, 48.2),
 (1, 1, 34.0, 1, 0, 1, 106.23, nan),
 (1, 1, 64.0, 1, 0, 0, 239.64, 34.6),
 (2, 1, 66.0, 0, 0, 0, 58.95, 24.6),
 (2, 0, 23.0, 0, 0, 0, 99.92, 25.8),
 (2, 1, 68.0, 1, 0, 0, 116.23, 26.1),
 (1, 1, 55.0, 0, 0, 0, 118.82, 29.0),
 (2, 0, 25.0, 0, 0, 0, 66.3, 27.2),
 (3, 0, 48.0, 0, 0, 0, 101.41, 20.7),
 (1, 1, 79.0, 0, 1, 1, 200.28, 30.0),
 (2, 1, 47.0, 0, 0, 0, 136.8, 37.3),
 (2, 0, 20.0, 0, 0, 0, 96.57, 34.1),
 (2, 1, 60.0, 0, 0, 0, 66.42, 23.6),
 (3, 1, 32.0, 0, 0, 0, 98.09, 25.2),
 (2, 1, 66.0, 0, 1, 0, 205.23, 39.5),
 (3, 1, 43.0, 1, 0, 0, 86.78, 23.5),
 (2, 0, 36.0, 0, 0, 0, 126.82, 23.3),
 (2, 1, 52.0, 1, 0, 0, 78.4, 64.8),
 (3, 1, 29.0, 0, 0, 0, 63.69, 28.1),
 (2, 1, 76.0, 0, 1, 0, 209.58, nan),
 (2, 1, 39.0, 0, 0, 0, 89.86, 24.4),
 (1, 1, 76.0, 1, 0, 0, 110.99, 29.8),
 (0, 0, 0.64, 0, 0, 0, 83.82, 24.9),
 (0, 1, 34.0, 1, 0, 0, 137.96, 35.1),
 (1, 1, 72.0, 0, 0, 0, 210.78, 32.3),
 (2, 1, 43.0, 0, 0, 0, 118.89, 43.6),
 (2, 0, 57.0, 0, 0, 0, 72.55, 21.0),
 (2, 1, 44.0, 0, 0, 0, 107.41, 47.3),
 (0, 0, 4.0, 0, 0, 0, 93.25, 16.6),
 (2, 1, 44.0, 1, 0, 0, 74.91, 37.5),
 (2, 0, 18.0, 0, 0, 0, 80.05, 24.2),
 (2, 1, 41.0, 1, 0, 0, 99.8, 31.6),
 (1, 1, 23.0, 0, 0, 0, 91.97, 21.6),
 (3, 1, 53.0, 0, 0, 0, 64.4, 31.0),
 (2, 1, 56.0, 1, 0, 0, 73.02, 31.1),
 (0, 0, 0.88, 0, 0, 0, 88.11, 15.5),
 (0, 0, 25.0, 1, 0, 0, 138.29, 27.3),
 (0, 0, 14.0, 0, 0, 0, 72.36, 20.5),
 (1, 1, 53.0, 0, 0, 0, 68.76, 35.6),
 (0, 0, 4.0, 1, 0, 0, 106.22, 16.7),
 (2, 1, 39.0, 0, 0, 0, 101.52, 41.8),
 (2, 1, 53.0, 1, 1, 1, 109.51, 41.9),
 (0, 0, 5.0, 1, 0, 0, 85.84, 16.4),
 (0, 0, 4.0, 1, 0, 0, 110.15, 17.1),
 (2, 1, 37.0, 0, 0, 0, 91.72, 29.2),
 (2, 1, 70.0, 1, 1, 0, 251.6, 27.1),
 (2, 0, 24.0, 1, 0, 0, 123.1, 37.9),
 (1, 1, 55.0, 1, 0, 0, 97.4, 44.6),
 (1, 1, 70.0, 0, 0, 0, 68.34, 22.8),
 (2, 1, 34.0, 1, 0, 0, 80.81, 33.2),
 (3, 1, 26.0, 1, 0, 0, 120.31, 22.3),
 (2, 1, 39.0, 0, 0, 0, 83.51, 26.4),
 (2, 0, 38.0, 1, 0, 0, 74.09, 39.6),
 (2, 0, 20.0, 0, 0, 0, 91.6, 28.1),
 (2, 0, 17.0, 0, 0, 0, 87.52, 39.2),
 (2, 1, 60.0, 1, 1, 0, 213.37, 36.0),
 (2, 1, 75.0, 0, 0, 0, 75.39, 37.8),
 (3, 1, 31.0, 0, 0, 0, 122.41, 40.3),
 (1, 1, 58.0, 1, 1, 0, 223.36, 41.5),
 (0, 0, 5.0, 0, 0, 0, 84.59, 17.7),
 (2, 0, 13.0, 0, 0, 0, 70.16, 21.2),
 (0, 0, 22.0, 0, 0, 0, 107.52, 41.6),
 (3, 1, 52.0, 0, 0, 0, 80.88, 23.8),
 (0, 1, 61.0, 0, 0, 0, 93.48, 23.7),
 (2, 1, 78.0, 0, 0, 1, 70.21, 24.8),
 (0, 1, 57.0, 1, 0, 0, 86.67, 39.0),
 (2, 1, 21.0, 0, 0, 0, 101.37, 37.9),
 (2, 1, 22.0, 0, 0, 0, 105.22, 31.1),
 (0, 1, 80.0, 0, 0, 0, 70.31, 23.2),
 (0, 0, 7.0, 1, 0, 0, 64.06, 18.9),
 (2, 1, 64.0, 1, 1, 0, 178.29, 36.1),
 (3, 0, 64.0, 0, 0, 0, 81.6, 36.3),
 (0, 1, 38.0, 0, 0, 0, 147.48, 40.5),
 (2, 0, 12.0, 1, 0, 0, 86.86, 25.4),
 (3, 1, 33.0, 0, 0, 0, 71.16, 46.5),
 (0, 0, 3.0, 0, 0, 0, 73.2, 16.8),
 (2, 1, 37.0, 0, 0, 0, 203.81, 46.6),
 (2, 0, 22.0, 0, 0, 0, 82.0, 26.4),
 (2, 0, 24.0, 0, 0, 0, 97.55, 26.2),
 (0, 1, 75.0, 1, 0, 0, 94.29, 35.2),
 (0, 0, 12.0, 0, 0, 0, 75.22, 20.9),
 (0, 1, 63.0, 1, 0, 0, 90.07, 36.8),
 (1, 1, 52.0, 0, 0, 0, 73.73, 34.4),
 (2, 1, 68.0, 0, 0, 0, 79.58, 22.2),
 (0, 0, 5.0, 0, 0, 0, 77.88, 13.8),
 (2, 1, 56.0, 0, 1, 0, 205.26, 40.3),
 (3, 1, 43.0, 0, 0, 0, 58.63, 28.4),
 (3, 1, 40.0, 0, 0, 0, 139.9, 31.7),
 (1, 1, 53.0, 1, 0, 0, 211.03, 34.2),
 (2, 1, 52.0, 0, 0, 1, 72.79, 54.7),
 (1, 1, 31.0, 1, 0, 0, 91.65, 24.6),
 (3, 1, 63.0, 0, 0, 0, 79.92, nan),
 (2, 1, 69.0, 0, 0, 0, 225.47, 36.9),
 (2, 1, 64.0, 1, 0, 0, 94.48, 31.1),
 (2, 1, 64.0, 0, 0, 0, 82.34, 31.9),
 (1, 1, 62.0, 0, 0, 0, 180.63, 31.8),
 (0, 0, 2.0, 0, 0, 0, 92.48, 18.0),
 (1, 1, 53.0, 1, 0, 0, 116.66, 28.5),
 (2, 1, 65.0, 1, 1, 0, 112.09, 29.5),
 (2, 0, 22.0, 0, 0, 0, 130.34, 22.0),
 (2, 0, 26.0, 0, 0, 0, 82.59, 29.4),
 (0, 1, 53.0, 1, 0, 0, 123.87, 28.8),
 (0, 0, 20.0, 1, 0, 0, 98.7, 26.2),
 (0, 1, 63.0, 0, 1, 0, 227.1, 26.9),
 (0, 0, 13.0, 1, 0, 0, 55.39, 23.2),
 (0, 0, 21.0, 1, 0, 0, 66.07, 27.9),
 (2, 1, 65.0, 0, 0, 0, 104.21, 36.8),
 (0, 1, 65.0, 1, 0, 0, 145.15, 28.9),
 (2, 1, 42.0, 1, 0, 0, 68.19, 31.0),
 (3, 1, 72.0, 1, 0, 1, 97.53, 29.4),
 (2, 0, 13.0, 1, 0, 0, 122.31, 15.3),
 (2, 0, 29.0, 1, 0, 0, 83.51, 37.1),
 (0, 1, 59.0, 1, 0, 0, 86.46, 30.5),
 (2, 1, 42.0, 0, 0, 0, 112.06, 38.2),
 (2, 0, 13.0, 1, 0, 0, 92.14, 23.2),
 (1, 0, 75.0, 1, 0, 1, 201.76, 30.2),
 (3, 1, 33.0, 0, 1, 0, 74.44, 45.2),
 (0, 1, 43.0, 0, 0, 0, 95.93, 21.8),
 (0, 0, 11.0, 0, 0, 0, 87.51, 24.4),
 (0, 0, 7.0, 0, 0, 0, 72.35, 17.0),
 (0, 0, 16.0, 0, 0, 0, 113.47, 19.5),
 (1, 0, 44.0, 0, 0, 0, 103.78, 49.8),
 (2, 1, 78.0, 0, 0, 0, 115.43, 27.8),
 (2, 1, 25.0, 1, 0, 0, 95.59, 25.1),
 (3, 1, 69.0, 1, 0, 0, 101.52, 26.8),
 (3, 1, 61.0, 0, 1, 0, 170.05, 60.2),
 (2, 0, 43.0, 0, 1, 0, 217.3, 27.5),
 (2, 1, 38.0, 0, 1, 0, 196.01, 28.1),
 (0, 1, 68.0, 1, 0, 0, 92.21, 27.3),
 (2, 1, 26.0, 1, 0, 0, 100.09, 27.4),
 (2, 0, 18.0, 0, 0, 0, 93.88, 22.2),
 (3, 1, 43.0, 0, 0, 0, 75.05, 22.9),
 (2, 1, 43.0, 0, 0, 0, 70.08, 26.6),
 (3, 0, 32.0, 0, 0, 0, 74.2, 23.0),
 (2, 0, 81.0, 0, 0, 0, 69.01, 32.6),
 (0, 0, 25.0, 1, 0, 0, 96.17, 22.1),
 (0, 1, 61.0, 1, 0, 0, 184.15, nan),
 (1, 1, 66.0, 0, 0, 0, 87.24, 22.5),
 (3, 1, 54.0, 1, 1, 0, 198.69, nan),
 (0, 0, 11.0, 1, 0, 0, 82.58, 25.5),
 (0, 1, 53.0, 0, 0, 0, 96.88, 31.4),
 (0, 1, 78.0, 0, 0, 1, 73.32, 26.0),
 (0, 0, 9.0, 1, 0, 0, 94.59, 20.0),
 (3, 1, 48.0, 0, 0, 0, 132.08, 31.6),
 (2, 1, 31.0, 0, 0, 0, 98.99, 31.2),
 (2, 0, 20.0, 1, 0, 0, 104.48, 21.7),
 (0, 1, 21.0, 1, 0, 0, 98.01, 24.2),
 (1, 1, 42.0, 0, 0, 0, 79.14, 25.0),
 (0, 1, 35.0, 1, 0, 0, 89.32, 36.7),
 (0, 0, 53.0, 1, 0, 0, 65.24, 28.9),
 (1, 1, 60.0, 1, 0, 0, 80.98, 29.7),
 (0, 1, 74.0, 1, 0, 0, 186.17, 44.3),
 (2, 0, 23.0, 0, 0, 0, 69.24, 51.0),
 (1, 1, 55.0, 0, 0, 0, 111.19, 39.7),
 (2, 1, 71.0, 0, 0, 0, 93.28, 34.7),
 (0, 0, 5.0, 1, 0, 0, 122.19, 35.0),
 (2, 0, 14.0, 0, 0, 0, 129.53, 21.3),
 (0, 0, 15.0, 0, 0, 0, 114.53, 29.1),
 (3, 0, 66.0, 0, 0, 0, 93.73, 23.9),
 (1, 1, 56.0, 0, 0, 0, 77.49, 36.0),
 (1, 1, 60.0, 0, 0, 0, 65.38, 41.2),
 (2, 1, 57.0, 0, 0, 0, 94.18, 27.1),
 (0, 1, 29.0, 1, 0, 0, 118.7, 33.2),
 (3, 1, 76.0, 0, 0, 0, 96.29, 25.4),
 (3, 1, 52.0, 1, 1, 0, 74.64, 30.7),
 (1, 1, 42.0, 0, 0, 0, 96.99, 34.8),
 (0, 1, 71.0, 0, 0, 0, 100.61, 19.2),
 (0, 1, 64.0, 1, 0, 0, 97.08, 31.7),
 (2, 1, 39.0, 0, 0, 0, 84.79, 35.7),
 (1, 1, 46.0, 0, 0, 0, 78.75, 37.8),
 (3, 1, 51.0, 0, 0, 0, 82.93, 29.7),
 (3, 1, 31.0, 1, 0, 0, 88.78, 35.8),
 (3, 0, 22.0, 1, 0, 0, 122.1, 23.6),
 (3, 0, 41.0, 1, 0, 0, 74.81, 39.7),
 (3, 1, 28.0, 0, 0, 0, 183.45, 40.5),
 (2, 1, 44.0, 0, 0, 0, 114.94, 21.4),
 (1, 1, 68.0, 0, 0, 0, 104.38, 40.8),
 (0, 1, 49.0, 1, 0, 0, 102.91, 24.7),
 (0, 0, 10.0, 1, 0, 0, 108.79, 21.0),
 (2, 1, 31.0, 0, 0, 0, 73.31, 45.0),
 (2, 1, 67.0, 1, 0, 0, 68.52, 26.2),
 (3, 1, 40.0, 1, 0, 0, 89.77, nan),
 (2, 1, 70.0, 1, 0, 0, 102.64, 28.3),
 (2, 1, 38.0, 0, 0, 0, 70.92, 41.6),
 (0, 0, 5.0, 0, 0, 0, 86.11, 19.0),
 (2, 1, 54.0, 0, 0, 0, 129.16, 32.4),
 (2, 1, 30.0, 0, 0, 0, 113.85, 34.0),
 (1, 1, 23.0, 0, 0, 0, 79.35, 39.4),
 (0, 1, 31.0, 0, 0, 0, 80.79, 28.7),
 (1, 1, 72.0, 1, 1, 0, 114.01, 31.8),
 (2, 0, 23.0, 1, 0, 0, 93.74, 31.2),
 (0, 1, 25.0, 0, 0, 0, 90.65, 20.9),
 (2, 1, 51.0, 1, 0, 0, 98.41, 32.1),
 (0, 0, 20.0, 0, 0, 0, 127.18, 31.0),
 (0, 0, 12.0, 0, 0, 0, 138.06, 23.1),
 (2, 1, 57.0, 1, 0, 0, 89.44, 26.7),

In [ ]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
model = GaussianNB()

# Train the model using the training sets
model.fit(features,stroke_target)

#Predict Output
predicted= model.predict([[0,1]]) # 0:Overcast, 2:Mild
print ("Predicted Value:", predicted)

ValueError: ignored

In [ ]:
x_data = features
y_data = stroke_target

In [ ]:
# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.3,random_state=109) # 70% training and 30% test

In [ ]:
#This is model generation

#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
model = GaussianNB()

#Train the model using the training sets
model.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = model.predict(X_test)

#This is to evaluate the model
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

ValueError: ignored

In [ ]:
#x_data = df[['gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
#      'avg_glucose_level', 'bmi', 'smoking_status']]
#y_data = df['stroke']